seeds:
############  WM - SEEDS        ############
#### TOPO WM - KBK - DEFAULT STYLE
  wm_kbk:
    caches: [cache_wm_seed]
    grids: [webmercator]
    coverages: ['kbk']
    levels:
      from: 11
      to: 16
    refresh_before:
      # days: 7
      minutes: 15

#### TOPO WM - KBK - ZWART/WIT STYLE
  wm_kbk_zw:
    caches: [cache_wm_seed_zw]
    grids: [webmercator]
    coverages: ['kbk']
    levels:
      from: 11
      to: 16
    refresh_before:
      # days: 7
      minutes: 15

#### TOPO WM - KBK - LIGHT STYLE
  wm_kbk_light:
    caches: [cache_wm_seed_light]
    grids: [webmercator]
    coverages: ['kbk']
    levels:
      from: 11
      to: 16
    refresh_before:
      # days: 7
      minutes: 15

############  RD - SEEDS        ############
#### TOPO RD - KBK - DEFAULT STYLE
  rd_kbk:
    caches: [cache_rd_seed]
    grids: [nl_grid]
    coverages: ['kbk']
    levels:
      from: 5
      to: 11
    refresh_before:
      # days: 7
      minutes: 15

#### TOPO RD - KBK - ZWART/WIT STYLE
  rd_kbk_zw:
    caches: [cache_rd_seed_zw]
    grids: [nl_grid]
    coverages: ['kbk']
    levels:
      from: 5
      to: 11
    refresh_before:
      # days: 7
      minutes: 15

#### TOPO RD - KBK - LIGHT STYLE
  rd_kbk_light:
    caches: [cache_rd_seed_light]
    grids: [nl_grid]
    coverages: ['kbk']
    levels:
      from: 5
      to: 11
    refresh_before:
      # days: 7
      minutes: 15


coverages:
  kbk:
    bbox: [94100,464250,170000,514160]
    srs: 'EPSG:28992'
  bgt:
    bbox: [104000,474000,136000,502100]
    srs: 'EPSG:28992'
