version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    volumes:
      - "$PWD/config/database:/database"
    ports:
      - "5402:5432"
    environment:
      POSTGRES_DB: basiskaart
      POSTGRES_USER: basiskaart
      POSTGRES_PASSWORD: insecure

  t_rex:
    image: sourcepole/t-rex
    ports:
      - "6767:6767"
    links:
      - database
    environment:
      DATABASE_NAME: basiskaart
      DATABASE_HOST: database
      DATABASE_USER: basiskaart
      DATABASE_PASSWORD: insecure
    volumes:
      - "$PWD/local/data/in:/var/data/in:ro"
      - "$PWD/local/data/out:/var/data/out"
      - "$PWD/local:/var/config:ro"
      - "$PWD/local/cache:/var/cache/mvtcache/wm"
      - "$PWD/local/static:/static"
    command: serve --config /var/config/topo_wm.toml
    # command: generate --minzoom=10 --maxzoom=10 --extent 4.64033750451671,52.2516789054116,5.10736113164264,52.5062589665124 --config /var/config/topo_rd.toml --loglevel info

  t_rex_rd:
    image: sourcepole/t-rex
    ports:
      - "6768:6767"
    links:
      - database
    environment:
      DATABASE_NAME: basiskaart
      DATABASE_HOST: database
      DATABASE_USER: basiskaart
      DATABASE_PASSWORD: insecure
    volumes:
      - "$PWD/local/data/in:/var/data/in:ro"
      - "$PWD/local/data/out:/var/data/out"
      - "$PWD/local:/var/config:ro"
      - "$PWD/local/cache:/var/cache/mvtcache"
      - "$PWD/local/static:/static"
    command: serve --config  /var/config/topo_rd.toml

  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8080:8080"
    links:
      - t_rex
      - t_rex_rd
    volumes:
      - "$PWD/local/data:/data"
      - "$PWD/local:/var/config:ro"
      - "$PWD/local/styles_direct:/static/styles_direct:ro"
      - "$PWD/tileserver/static/fonts:/static/fonts:ro"
    command: -p 8080 --verbose -c /var/config/tileserver_cfg.json

  mapproxy:
    build: 
      context: mapproxy
    ports:
      - "8000:8000"
    links: 
      - tileserver
    volumes:
      - "$PWD/local:/var/config:ro"
    environment:
      UWSGI_HTTP: "0.0.0.0:8000"
      UWSGI_MASTER: 1
      UWSGI_PROCESSES: 4

  mapproxy_wm_seed:
    build:
      context: mapproxy
    user: root
    links:
      - tileserver
    volumes:
      - "$PWD/local:/var/config:ro"
      - "$PWD/local/tiles:/mnt/tiles"
    command: >
      mapproxy-seed -c 4 -s /var/config/seed.yaml -f /var/config/mapproxy.yaml --seed=rd_kbk,rd_bgt
